export const COLORS = [
  // Нейтральные / Neutre
  { hex: '#000000', name: { ru: 'Чёрный',            ro: 'Negru' } },
  { hex: '#2C2C2C', name: { ru: 'Антрацит',          ro: 'Antracit' } },
  { hex: '#555555', name: { ru: 'Графитовый',        ro: 'Grafit' } },
  { hex: '#808080', name: { ru: 'Серый',             ro: 'Gri' } },
  { hex: '#C8C8C8', name: { ru: 'Светло-серый',      ro: 'Gri deschis' } },
  { hex: '#FFFFFF', name: { ru: 'Белый',             ro: 'Alb' } },
  { hex: '#F5F0E8', name: { ru: 'Молочный',          ro: 'Alb lăptos' } },
  { hex: '#FFFDD0', name: { ru: 'Кремовый',          ro: 'Crem' } },
  { hex: '#D4BFA0', name: { ru: 'Бежевый',           ro: 'Bej' } },
  { hex: '#C2A97D', name: { ru: 'Песочный',          ro: 'Nisipiu' } },
  { hex: '#B59A7A', name: { ru: 'Капучино',          ro: 'Cappuccino' } },
  { hex: '#C68642', name: { ru: 'Карамельный',       ro: 'Caramel' } },
  // Коричневые / Maro
  { hex: '#A0724A', name: { ru: 'Светло-коричневый', ro: 'Maro deschis' } },
  { hex: '#8B4513', name: { ru: 'Коричневый',        ro: 'Maro' } },
  { hex: '#5C3317', name: { ru: 'Шоколадный',        ro: 'Ciocolatiu' } },
  { hex: '#3B1E08', name: { ru: 'Тёмно-коричневый',  ro: 'Maro închis' } },
  // Зелёные / Verde
  { hex: '#8F9E7B', name: { ru: 'Шалфей',            ro: 'Salvie' } },
  { hex: '#78866B', name: { ru: 'Хаки',              ro: 'Kaki' } },
  { hex: '#6B7B3A', name: { ru: 'Оливковый',         ro: 'Olive' } },
  { hex: '#2D5A27', name: { ru: 'Хвойный',           ro: 'Verde conifer' } },
  { hex: '#1A4A1A', name: { ru: 'Тёмно-зелёный',     ro: 'Verde închis' } },
  { hex: '#2E8B57', name: { ru: 'Зелёный',           ro: 'Verde' } },
  { hex: '#009B77', name: { ru: 'Изумрудный',        ro: 'Smarald' } },
  { hex: '#6DB88F', name: { ru: 'Мятный',            ro: 'Mentă' } },
  // Синие / Albastru
  { hex: '#003366', name: { ru: 'Тёмно-синий',       ro: 'Bleumarin' } },
  { hex: '#1E40AF', name: { ru: 'Синий',             ro: 'Albastru' } },
  { hex: '#0F52BA', name: { ru: 'Сапфировый',        ro: 'Safir' } },
  { hex: '#4A6FA5', name: { ru: 'Джинсовый',         ro: 'Denim' } },
  { hex: '#5B7C99', name: { ru: 'Стальной',          ro: 'Oțel' } },
  { hex: '#7B9EB4', name: { ru: 'Серо-голубой',      ro: 'Albastru-gri' } },
  { hex: '#4A90D9', name: { ru: 'Голубой',           ro: 'Albastru deschis' } },
  { hex: '#ADD8E6', name: { ru: 'Небесный',          ro: 'Bleu' } },
  // Фиолетовые / Violet
  { hex: '#660066', name: { ru: 'Сливовый',          ro: 'Prună' } },
  { hex: '#6B21A8', name: { ru: 'Фиолетовый',        ro: 'Violet' } },
  { hex: '#967BB6', name: { ru: 'Лавандовый',        ro: 'Lavandă' } },
  { hex: '#C3A9C8', name: { ru: 'Сиреневый',         ro: 'Liliachiu' } },
  // Красные / бордовые / Roșu
  { hex: '#8B0000', name: { ru: 'Тёмно-красный',     ro: 'Roșu închis' } },
  { hex: '#800020', name: { ru: 'Бордовый',          ro: 'Bordo' } },
  { hex: '#990000', name: { ru: 'Вишнёвый',          ro: 'Vișiniu' } },
  { hex: '#CC0000', name: { ru: 'Красный',           ro: 'Roșu' } },
  { hex: '#C2185B', name: { ru: 'Малиновый',         ro: 'Zmeură' } },
  { hex: '#CC5533', name: { ru: 'Терракотовый',      ro: 'Teracotă' } },
  { hex: '#E2725B', name: { ru: 'Коралловый',        ro: 'Coral' } },
  // Розовые / Roz
  { hex: '#C48B9F', name: { ru: 'Пыльная роза',      ro: 'Roz prăfuit' } },
  { hex: '#DBADB4', name: { ru: 'Пудровый',          ro: 'Pudrat' } },
  { hex: '#E88FA3', name: { ru: 'Розовый',           ro: 'Roz' } },
  { hex: '#C71585', name: { ru: 'Тёмно-розовый',     ro: 'Roz închis' } },
  { hex: '#FF0095', name: { ru: 'Фуксия',            ro: 'Fucsia' } },
  // Жёлтые / оранжевые / Galben–portocaliu
  { hex: '#C8960C', name: { ru: 'Горчичный',         ro: 'Muștar' } },
  { hex: '#CC7722', name: { ru: 'Охра',              ro: 'Ocru' } },
  { hex: '#D4581A', name: { ru: 'Оранжевый',         ro: 'Portocaliu' } },
]